### ISSUE TITLE
Integrate with the new archive

### ISSUE THREAD

**Issue by osheinin** [Bnei-Baruch/BBLessonsDownloader#2]

**Comment by osheinin** [comment]
@edoshor, can you provide interface?

**Comment by edoshor** [comment]
base api url is `https://archive.kbb1.com/backend/`.

To get the list of lesson parts do this
```
https://archive.kbb1.com/backend/content_units?page_no=1&page_size=10&content_type=LESSON_PART&language=en
```

note the pagination and language params.


This would only give you the content_units, not their files. For that you'll have to make a different call to get the full details of each content_unit:

```
https://archive.kbb1.com/backend/content_units/w7SeROrR
```

Once you get these, you'll have to iterate the files to find the ones you're looking for.

**Comment by osheinin** [comment]
How can I retrieve the files from specific date?

**Comment by alexmbb** [comment]
@osheinin 
Did you implemented this? We are going to close the old site this week

**Comment by osheinin** [comment]
Done
